/**
 * Created by david on 02/03/2017.
 */
const START_DOWNLOAD = "START_DOWNLOAD";
const STOP_DOWNLOAD = "STOP_DOWNLOAD";
const PAUSE_DOWNLOAD = "PAUSE_DOWNLOAD";
const RESUME_DOWNLOAD = "RESUME_DOWNLOAD";
const CANCEL_DOWNLOAD = "CANCEL_DOWNLOAD";
const START_RENAME = "START_RENAME";
const RENAME_COMPLETED = "RENAME_COMPLETED";
const STOP_RENAME = "STOP_RENAME";
const START_SUBTITLES = "START_SUBTITLES";
const STOP_SUBTITLES = "STOP_SUBTITLES";
const STATUS = "STATUS";
const RESPONSE = "RESPONSE";

module.exports = { START_DOWNLOAD,STOP_DOWNLOAD,PAUSE_DOWNLOAD,RESUME_DOWNLOAD,
                    CANCEL_DOWNLOAD,START_RENAME,STOP_RENAME,START_SUBTITLES,
                    STOP_SUBTITLES,STATUS,RENAME_COMPLETED,RESPONSE};